### ISSUE TITLE
On first register: PHP Fatal error:  Call to a member function fetch_array() on boolean in [...]/emoncms/Modules/user/user_model.php on line 473, referer: [...]/user/login

### ISSUE THREAD

**Issue by beaylott** [emoncms/emoncmsorg#2]
Hey I am trying to setup the emoncms.org version based off this master and I am getting this error in apache log. It looks sort of like it is trying to login instead of register but then there are no users in the table so it is returning 'false' from the SQL query. Do I need to manually create the first user in this version?

**Comment by TrystanLea** [comment]
Hello Ben, i think you just need to set $dbtest to true here: 
https://github.com/emoncms/emoncmsorg/blob/master/emoncms/default.settings.php#L80

**Comment by beaylott** [comment]
doh yes of course thanks
