### ISSUE TITLE
Pulse count to pulse increment input processor

### ISSUE THREAD

**Issue by danbates2** [emoncms/emoncmsorg#26]
Not sure if it's working. Seems to reset with a pulse count reset.
Behaviour like Wh accumulator I think might be the idea?
Might even be worth scrapping the processor, could even rename Wh_accumulator to just Accumulator for accumulating data in general.

**Comment by TrystanLea** [comment]
this process is not available on emoncms.org, but will consider disabling on emoncms core as I dont think this process adds that much really.
