### ISSUE TITLE
Can't setup input queue processor - is file out of date?

### ISSUE THREAD

**Issue by beaylott** [emoncms/emoncmsorg#3]
In lieu of instructions for setting up the input queue processor for an emoncms.org I have been trying to work it out myself. The file in the repo (https://github.com/emoncms/emoncmsorg/blob/master/MainServerScripts/inputqueue_processor.php) seems out of date because it refers to a emoncms/Modules/log which doesn't exist. Where is the EmonLogger provided in this case? Should I try to use an alternate?

**Comment by TrystanLea** [comment]
Hello Ben, I've updated with the latest changes from emoncms.org including quite a few changes to scripts. You shouldnt need to use more than one input queue processor or more than storageserver0 for now.

We are putting together a docker image that should allow for easy deployment of this. But its not quite there yet. 

The latest update contains updates to default.settings.php that you will want to copy over

**Comment by TrystanLea** [comment]
I've started documenting the setup procedure here:
https://github.com/emoncms/emoncmsorg/blob/master/readme.md

**Comment by TrystanLea** [comment]
The readme now includes instructions for setting up an inputqueue and storageserver0 which is writing data to the local server rather than a separate storage server service.

**Comment by beaylott** [comment]
Thanks for updating code/instructions. Will try very soon!
