### ISSUE TITLE
Deleted Feed still shows up in the old graph that was created via Visualization page.

### ISSUE THREAD

**Issue by minida28** [emoncms/emoncmsorg#4]
Hi,
I deleted one of the feed, but it still shows up in the previous graph I created in Visualization page.
It then throws error: `Request error {"success":false,"message":"Feed does not exist"}`

![zz](https://cloud.githubusercontent.com/assets/3026584/23025602/11ae5040-f491-11e6-977c-c68254154f22.PNG)

I can simply delete the problematic graph and re-create it.
But it would be better if the emoncms automatically update the missing feed.

Thanks!

**Comment by glynhudson** [comment]
Thanks for letting us know, however, this behaviour is by design. IMO is better than Emoncms lets alerts the users that one of the feeds from that graph is missing rather than just removing the feed from the graph without alerting the user.

**Comment by minida28** [comment]
Thanks @glynhudson
